/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   api-xml-schema-render.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/utils/render-status.d.ts" />
/// <reference path="../prism-element/prism-theme-default.d.ts" />

declare class ApiXmlSchemaRender extends Polymer.Element {

  /**
   * Data to render.
   */
  code: string|null|undefined;

  /**
   * Handles highlighting when code changed.
   * Note that the operation is async.
   */
  _codeChanged(code: String|null): void;

  /**
   * Dispatches `syntax-highlight` custom event
   *
   * @param code Code to highlight
   * @returns Highlighted code.
   */
  highlight(code: String|null): String|null;
}

interface HTMLElementTagNameMap {
  "api-xml-schema-render": ApiXmlSchemaRender;
}
