/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   api-schema-render.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

import {afterNextRender} from '@polymer/polymer/lib/utils/render-status.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

declare class ApiSchemaRender extends PolymerElement {

  /**
   * Data to render.
   */
  code: string|null|undefined;
  readonly type: string|null|undefined;

  /**
   * Handles highlighting when code changed.
   * Note that the operation is async.
   */
  _codeChanged(code: String|null): void;

  /**
   * Dispatches `syntax-highlight` custom event
   *
   * @param code Code to highlight
   * @returns Highlighted code.
   */
  highlight(code: String|null): String|null;
  _clearTypeAttribute(): void;
  _typeChanged(type: any): void;
}

declare global {

  interface HTMLElementTagNameMap {
    "api-schema-render": ApiSchemaRender;
  }
}
