headers: 
  X-HSBC-E2E-Trust-Token:
    description: Contains Identity information about the authentication caller (or subject)
    required: false
  X-HSBC-Session-Id:
    description: Contains the identifier which represents a subject's authenticated session with an Identity Provider
    required: false